# shellcheck shell=bash
# The anti-lockout dead-man's switch (§9.4, D10). When server-setup performs the
# SSH cutover (root off / password off), it arms a `systemd-run --on-active`
# timer that RESTORES the previous SSH drop-in and reloads sshd unless you run
# `server confirm` in time. Reconnect as the deploy user, confirm, and the timer
# is cancelled; do nothing and SSH rolls back to its pre-cutover state.
#
# Reboot-edge (assumed & documented, §9.4): the timer is a transient systemd
# unit held in memory. A reboot during the window loses it — so the rule is
# "confirm BEFORE any reboot".

DEADMAN_UNIT="server-setup-deadman"
DEADMAN_ROLLBACK_SCRIPT="$STATE_DIR/ssh-rollback.sh"
DEADMAN_WINDOW_DEFAULT="10min"

# deadman_render_rollback <dropin> <prev-snapshot-or-empty> -> print the rollback
# script to stdout. Pure (no I/O beyond stdout), so it is unit-testable without
# systemd. If <prev-snapshot> is non-empty the rollback restores it; otherwise
# the drop-in did not exist before, so the rollback removes it.
deadman_render_rollback() {
  local dropin="$1" prev="$2"
  printf '#!/usr/bin/env bash\n'
  printf '# Auto-generated by server-setup — SSH anti-lockout rollback. Do not edit.\n'
  printf 'set -u\n'
  if [[ -n "$prev" ]]; then
    printf 'cp -a -- %q %q\n' "$prev" "$dropin"
  else
    printf 'rm -f -- %q\n' "$dropin"
  fi
  printf 'systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true\n'
  printf 'logger -t server-setup "anti-lockout fired: restored the previous SSH drop-in (no confirm within the window)"\n'
}

# deadman_arm <dropin> <prev-snapshot-or-empty> [window] -> write the rollback
# script and schedule it via systemd-run. Re-arming first clears any stale
# instance, so it is idempotent.
deadman_arm() {
  local dropin="$1" prev="$2" window="${3:-$DEADMAN_WINDOW_DEFAULT}"
  mkdir -p "$STATE_DIR"
  deadman_render_rollback "$dropin" "$prev" >"$DEADMAN_ROLLBACK_SCRIPT"
  chmod 0700 "$DEADMAN_ROLLBACK_SCRIPT"
  deadman_disarm
  # AccuracySec=1s: systemd timers default to 1-minute accuracy, which would let
  # the rollback fire up to a minute late. Pin it tight so the window is honest.
  systemd-run --on-active="$window" --timer-property=AccuracySec=1s \
    --unit="$DEADMAN_UNIT" --collect \
    --description="server-setup SSH anti-lockout rollback" \
    "$DEADMAN_ROLLBACK_SCRIPT" >/dev/null 2>&1 ||
    die "deadman: failed to arm the systemd-run timer"
}

# deadman_disarm -> cancel a pending timer/service if present. Safe to call when
# nothing is armed (used by `server confirm` and before re-arming).
deadman_disarm() {
  systemctl stop "${DEADMAN_UNIT}.timer" >/dev/null 2>&1 || true
  systemctl stop "${DEADMAN_UNIT}.service" >/dev/null 2>&1 || true
  systemctl reset-failed "${DEADMAN_UNIT}.timer" >/dev/null 2>&1 || true
  systemctl reset-failed "${DEADMAN_UNIT}.service" >/dev/null 2>&1 || true
}

# deadman_is_armed -> true when the timer is still pending.
deadman_is_armed() {
  systemctl is-active --quiet "${DEADMAN_UNIT}.timer" 2>/dev/null
}
